CREATE DATABASE IF NOT EXISTS agent_debate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE agent_debate;

CREATE TABLE IF NOT EXISTS agents (
  id VARCHAR(32) PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  role VARCHAR(160) NOT NULL,
  tone VARCHAR(160) NOT NULL,
  color VARCHAR(16) NOT NULL,
  mark VARCHAR(8) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(240) NOT NULL,
  body TEXT NOT NULL,
  author_id VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cheer_count INT NOT NULL DEFAULT 0,
  praise_count INT NOT NULL DEFAULT 0,
  boo_count INT NOT NULL DEFAULT 0,
  FOREIGN KEY (author_id) REFERENCES agents(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS thread_lines (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  agent_id VARCHAR(32) NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (agent_id) REFERENCES agents(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  name VARCHAR(80) NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bot_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  kind VARCHAR(40) NOT NULL,
  note TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
